# Generated by Django 4.1.5 on 2023-01-22 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "Motorcycle"),
                            ("auto", "Auto"),
                            ("truck", "Truck"),
                            ("car", "Car"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "invoice_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, max_length=10),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, max_length=10),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("neft", "NEFT"),
                            ("rtgs", "RTGS"),
                            ("imps", "IMPS"),
                            ("upi", "UPI"),
                            ("paytm", "Paytm"),
                            ("points", "Points"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("is_points_redeemed", models.BooleanField(default=False)),
                ("redeemed_points", models.PositiveBigIntegerField(default=0)),
                ("points_earned", models.PositiveBigIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RewardPoints",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("points", models.PositiveBigIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward Point",
                "verbose_name_plural": "Reward Points",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "Motorcycle"),
                            ("auto", "Auto"),
                            ("truck", "Truck"),
                            ("car", "Car"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "invoice_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, max_length=10),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, max_length=10),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("neft", "NEFT"),
                            ("rtgs", "RTGS"),
                            ("imps", "IMPS"),
                            ("upi", "UPI"),
                            ("paytm", "Paytm"),
                            ("points", "Points"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("is_points_redeemed", models.BooleanField(default=False)),
                ("redeemed_points", models.PositiveBigIntegerField(default=0)),
                ("points_earned", models.PositiveBigIntegerField(default=0)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Transaction",
                "verbose_name_plural": "historical Transactions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRewardPoints",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("points", models.PositiveBigIntegerField(default=0)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Reward Point",
                "verbose_name_plural": "historical Reward Points",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="rewardpoints",
            index=models.Index(fields=["points"], name="transaction_points_75cb8f_idx"),
        ),
    ]
